name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
      image: bitnami/postgresql
      ports:
        - 5432:5432
      env:
        - POSTGRESQL_USERNAME=docker
        - POSTGRESQL_PASSWORD=docker
        - POSTGRESQL_DATABASE=api-solid

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run test script
        run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: 'postgresql://docker:docker@localhost:5432/api-solid?schema=public'
